using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace MigrationsPostgreSQL.Migrations
{
    /// <inheritdoc />
    public partial class Init : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "AspNetRoles",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    Name = table.Column<string>(type: "character varying(256)", maxLength: 256, nullable: true),
                    NormalizedName = table.Column<string>(type: "character varying(256)", maxLength: 256, nullable: true),
                    ConcurrencyStamp = table.Column<string>(type: "text", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AspNetRoles", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "AspNetUsers",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    Name = table.Column<string>(type: "text", nullable: false),
                    UserName = table.Column<string>(type: "character varying(256)", maxLength: 256, nullable: true),
                    NormalizedUserName = table.Column<string>(type: "character varying(256)", maxLength: 256, nullable: true),
                    Email = table.Column<string>(type: "character varying(256)", maxLength: 256, nullable: true),
                    NormalizedEmail = table.Column<string>(type: "character varying(256)", maxLength: 256, nullable: true),
                    EmailConfirmed = table.Column<bool>(type: "boolean", nullable: false),
                    PasswordHash = table.Column<string>(type: "text", nullable: true),
                    SecurityStamp = table.Column<string>(type: "text", nullable: true),
                    ConcurrencyStamp = table.Column<string>(type: "text", nullable: true),
                    PhoneNumber = table.Column<string>(type: "text", nullable: true),
                    PhoneNumberConfirmed = table.Column<bool>(type: "boolean", nullable: false),
                    TwoFactorEnabled = table.Column<bool>(type: "boolean", nullable: false),
                    LockoutEnd = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    LockoutEnabled = table.Column<bool>(type: "boolean", nullable: false),
                    AccessFailedCount = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AspNetUsers", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Organizations",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    DateCreated = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    Name = table.Column<string>(type: "character varying(450)", maxLength: 450, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Organizations", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Provinces",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    Name = table.Column<string>(type: "character varying(450)", maxLength: 450, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Provinces", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "AspNetRoleClaims",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    RoleId = table.Column<Guid>(type: "uuid", nullable: false),
                    ClaimType = table.Column<string>(type: "text", nullable: true),
                    ClaimValue = table.Column<string>(type: "text", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AspNetRoleClaims", x => x.Id);
                    table.ForeignKey(
                        name: "FK_AspNetRoleClaims_AspNetRoles_RoleId",
                        column: x => x.RoleId,
                        principalTable: "AspNetRoles",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "AspNetUserClaims",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    UserId = table.Column<Guid>(type: "uuid", nullable: false),
                    ClaimType = table.Column<string>(type: "text", nullable: true),
                    ClaimValue = table.Column<string>(type: "text", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AspNetUserClaims", x => x.Id);
                    table.ForeignKey(
                        name: "FK_AspNetUserClaims_AspNetUsers_UserId",
                        column: x => x.UserId,
                        principalTable: "AspNetUsers",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "AspNetUserLogins",
                columns: table => new
                {
                    LoginProvider = table.Column<string>(type: "text", nullable: false),
                    ProviderKey = table.Column<string>(type: "text", nullable: false),
                    ProviderDisplayName = table.Column<string>(type: "text", nullable: true),
                    UserId = table.Column<Guid>(type: "uuid", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AspNetUserLogins", x => new { x.LoginProvider, x.ProviderKey });
                    table.ForeignKey(
                        name: "FK_AspNetUserLogins_AspNetUsers_UserId",
                        column: x => x.UserId,
                        principalTable: "AspNetUsers",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "AspNetUserRoles",
                columns: table => new
                {
                    UserId = table.Column<Guid>(type: "uuid", nullable: false),
                    RoleId = table.Column<Guid>(type: "uuid", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AspNetUserRoles", x => new { x.UserId, x.RoleId });
                    table.ForeignKey(
                        name: "FK_AspNetUserRoles_AspNetRoles_RoleId",
                        column: x => x.RoleId,
                        principalTable: "AspNetRoles",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_AspNetUserRoles_AspNetUsers_UserId",
                        column: x => x.UserId,
                        principalTable: "AspNetUsers",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "AspNetUserTokens",
                columns: table => new
                {
                    UserId = table.Column<Guid>(type: "uuid", nullable: false),
                    LoginProvider = table.Column<string>(type: "text", nullable: false),
                    Name = table.Column<string>(type: "text", nullable: false),
                    Value = table.Column<string>(type: "text", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AspNetUserTokens", x => new { x.UserId, x.LoginProvider, x.Name });
                    table.ForeignKey(
                        name: "FK_AspNetUserTokens_AspNetUsers_UserId",
                        column: x => x.UserId,
                        principalTable: "AspNetUsers",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "Cities",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    Name = table.Column<string>(type: "character varying(450)", maxLength: 450, nullable: false),
                    ProvinceId = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Cities", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Cities_Provinces_ProvinceId",
                        column: x => x.ProvinceId,
                        principalTable: "Provinces",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "Services",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    DateCreated = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    Name = table.Column<string>(type: "character varying(450)", maxLength: 450, nullable: false),
                    Address = table.Column<string>(type: "text", nullable: false),
                    CityId = table.Column<int>(type: "integer", nullable: false),
                    PhoneNumber = table.Column<string>(type: "character(10)", unicode: false, fixedLength: true, maxLength: 10, nullable: true),
                    OrganizationId = table.Column<Guid>(type: "uuid", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Services", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Services_Cities_CityId",
                        column: x => x.CityId,
                        principalTable: "Cities",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_Services_Organizations_OrganizationId",
                        column: x => x.OrganizationId,
                        principalTable: "Organizations",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                table: "Provinces",
                columns: new[] { "Id", "Name" },
                values: new object[,]
                {
                    { 1, "Adana" },
                    { 2, "Adıyaman" },
                    { 3, "Afyonkarahisar" },
                    { 4, "Ağrı" },
                    { 5, "Amasya" },
                    { 6, "Ankara" },
                    { 7, "Antalya" },
                    { 8, "Artvin" },
                    { 9, "Aydın" },
                    { 10, "Balıkesir" },
                    { 11, "Bilecik" },
                    { 12, "Bingöl" },
                    { 13, "Bitlis" },
                    { 14, "Bolu" },
                    { 15, "Burdur" },
                    { 16, "Bursa" },
                    { 17, "Çanakkale" },
                    { 18, "Çankırı" },
                    { 19, "Çorum" },
                    { 20, "Denizli" },
                    { 21, "Diyarbakır" },
                    { 22, "Edirne" },
                    { 23, "Elazığ" },
                    { 24, "Erzincan" },
                    { 25, "Erzurum" },
                    { 26, "Eskişehir" },
                    { 27, "Gaziantep" },
                    { 28, "Giresun" },
                    { 29, "Gümüşhane" },
                    { 30, "Hakkari" },
                    { 31, "Hatay" },
                    { 32, "Isparta" },
                    { 33, "Mersin" },
                    { 34, "İstanbul" },
                    { 35, "İzmir" },
                    { 36, "Kars" },
                    { 37, "Kastamonu" },
                    { 38, "Kayseri" },
                    { 39, "Kırklareli" },
                    { 40, "Kırşehir" },
                    { 41, "Kocaeli" },
                    { 42, "Konya" },
                    { 43, "Kütahya" },
                    { 44, "Malatya" },
                    { 45, "Manisa" },
                    { 46, "Kahramanmaraş" },
                    { 47, "Mardin" },
                    { 48, "Muğla" },
                    { 49, "Muş" },
                    { 50, "Nevşehir" },
                    { 51, "Niğde" },
                    { 52, "Ordu" },
                    { 53, "Rize" },
                    { 54, "Sakarya" },
                    { 55, "Samsun" },
                    { 56, "Siirt" },
                    { 57, "Sinop" },
                    { 58, "Sivas" },
                    { 59, "Tekirdağ" },
                    { 60, "Tokat" },
                    { 61, "Trabzon" },
                    { 62, "Tunceli" },
                    { 63, "Şanlıurfa" },
                    { 64, "Uşak" },
                    { 65, "Van" },
                    { 66, "Yozgat" },
                    { 67, "Zonguldak" },
                    { 68, "Aksaray" },
                    { 69, "Bayburt" },
                    { 70, "Karaman" },
                    { 71, "Kırıkkale" },
                    { 72, "Batman" },
                    { 73, "Şırnak" },
                    { 74, "Bartın" },
                    { 75, "Ardahan" },
                    { 76, "Iğdır" },
                    { 77, "Yalova" },
                    { 78, "Karabük" },
                    { 79, "Kilis" },
                    { 80, "Osmaniye" },
                    { 81, "Düzce" }
                });

            migrationBuilder.InsertData(
                table: "Cities",
                columns: new[] { "Id", "Name", "ProvinceId" },
                values: new object[,]
                {
                    { 1, "Seyhan", 1 },
                    { 2, "Yüreğir", 1 },
                    { 3, "Sarıçam", 1 },
                    { 4, "Çukurova", 1 },
                    { 5, "Aladağ(Karsantı)", 1 },
                    { 6, "Ceyhan", 1 },
                    { 7, "Feke", 1 },
                    { 8, "İmamoğlu", 1 },
                    { 9, "Karaisalı", 1 },
                    { 10, "Karataş", 1 },
                    { 11, "Kozan", 1 },
                    { 12, "Pozantı", 1 },
                    { 13, "Saimbeyli", 1 },
                    { 14, "Tufanbeyli", 1 },
                    { 15, "Yumurtalık", 1 },
                    { 16, "Adıyaman", 2 },
                    { 17, "Besni", 2 },
                    { 18, "Çelikhan", 2 },
                    { 19, "Gerger", 2 },
                    { 20, "Gölbaşı", 2 },
                    { 21, "Kahta", 2 },
                    { 22, "Samsat", 2 },
                    { 23, "Sincik", 2 },
                    { 24, "Tut", 2 },
                    { 25, "Afyonkarahisar", 3 },
                    { 26, "Başmakçı", 3 },
                    { 27, "Bayat", 3 },
                    { 28, "Bolvadin", 3 },
                    { 29, "Çay", 3 },
                    { 30, "Çobanlar", 3 },
                    { 31, "Dazkırı", 3 },
                    { 32, "Dinar", 3 },
                    { 33, "Emirdağ", 3 },
                    { 34, "Evciler", 3 },
                    { 35, "Hocalar", 3 },
                    { 36, "İhsaniye", 3 },
                    { 37, "İscehisar", 3 },
                    { 38, "Kızılören", 3 },
                    { 39, "Sandıklı", 3 },
                    { 40, "Sincanlı(Sinanpaşa)", 3 },
                    { 41, "Sultandağı", 3 },
                    { 42, "Şuhut", 3 },
                    { 43, "Ağrı", 4 },
                    { 44, "Diyadin", 4 },
                    { 45, "Doğubeyazıt", 4 },
                    { 46, "Eleşkirt", 4 },
                    { 47, "Hamur", 4 },
                    { 48, "Patnos", 4 },
                    { 49, "Taşlıçay", 4 },
                    { 50, "Tutak", 4 },
                    { 51, "Amasya", 5 },
                    { 52, "Göynücek", 5 },
                    { 53, "Gümüşhacıköy", 5 },
                    { 54, "Hamamözü", 5 },
                    { 55, "Merzifon", 5 },
                    { 56, "Suluova", 5 },
                    { 57, "Taşova", 5 },
                    { 58, "Altındağ", 6 },
                    { 59, "Çankaya", 6 },
                    { 60, "Etimesgut", 6 },
                    { 61, "Keçiören", 6 },
                    { 62, "Mamak", 6 },
                    { 63, "Sincan", 6 },
                    { 64, "Yenimahalle", 6 },
                    { 65, "Gölbaşı", 6 },
                    { 66, "Pursaklar", 6 },
                    { 67, "Akyurt", 6 },
                    { 68, "Ayaş", 6 },
                    { 69, "Bala", 6 },
                    { 70, "Beypazarı", 6 },
                    { 71, "Çamlıdere", 6 },
                    { 72, "Çubuk", 6 },
                    { 73, "Elmadağ", 6 },
                    { 74, "Evren", 6 },
                    { 75, "Güdül", 6 },
                    { 76, "Haymana", 6 },
                    { 77, "Kalecik", 6 },
                    { 78, "Kazan", 6 },
                    { 79, "Kızılcahamam", 6 },
                    { 80, "Nallıhan", 6 },
                    { 81, "Polatlı", 6 },
                    { 82, "Şereflikoçhisar", 6 },
                    { 83, "Muratpaşa", 7 },
                    { 84, "Kepez", 7 },
                    { 85, "Konyaaltı", 7 },
                    { 86, "Aksu", 7 },
                    { 87, "Döşemealtı", 7 },
                    { 88, "Akseki", 7 },
                    { 89, "Alanya", 7 },
                    { 90, "Elmalı", 7 },
                    { 91, "Finike", 7 },
                    { 92, "Gazipaşa", 7 },
                    { 93, "Gündoğmuş", 7 },
                    { 94, "İbradı(Aydınkent)", 7 },
                    { 95, "Kale(Demre)", 7 },
                    { 96, "Kaş", 7 },
                    { 97, "Kemer", 7 },
                    { 98, "Korkuteli", 7 },
                    { 99, "Kumluca", 7 },
                    { 100, "Manavgat", 7 },
                    { 101, "Serik", 7 },
                    { 102, "Artvin", 8 },
                    { 103, "Ardanuç", 8 },
                    { 104, "Arhavi", 8 },
                    { 105, "Borçka", 8 },
                    { 106, "Hopa", 8 },
                    { 107, "Murgul(Göktaş)", 8 },
                    { 108, "Şavşat", 8 },
                    { 109, "Yusufeli", 8 },
                    { 110, "Aydın", 9 },
                    { 111, "Bozdoğan", 9 },
                    { 112, "Buharkent(Çubukdağı)", 9 },
                    { 113, "Çine", 9 },
                    { 114, "Germencik", 9 },
                    { 115, "İncirliova", 9 },
                    { 116, "Karacasu", 9 },
                    { 117, "Karpuzlu", 9 },
                    { 118, "Koçarlı", 9 },
                    { 119, "Köşk", 9 },
                    { 120, "Kuşadası", 9 },
                    { 121, "Kuyucak", 9 },
                    { 122, "Nazilli", 9 },
                    { 123, "Söke", 9 },
                    { 124, "Sultanhisar", 9 },
                    { 125, "Didim(Yenihisar)", 9 },
                    { 126, "Yenipazar", 9 },
                    { 127, "Balıkesir", 10 },
                    { 128, "Ayvalık", 10 },
                    { 129, "Balya", 10 },
                    { 130, "Bandırma", 10 },
                    { 131, "Bigadiç", 10 },
                    { 132, "Burhaniye", 10 },
                    { 133, "Dursunbey", 10 },
                    { 134, "Edremit", 10 },
                    { 135, "Erdek", 10 },
                    { 136, "Gömeç", 10 },
                    { 137, "Gönen", 10 },
                    { 138, "Havran", 10 },
                    { 139, "İvrindi", 10 },
                    { 140, "Kepsut", 10 },
                    { 141, "Manyas", 10 },
                    { 142, "Marmara", 10 },
                    { 143, "Savaştepe", 10 },
                    { 144, "Sındırgı", 10 },
                    { 145, "Susurluk", 10 },
                    { 146, "Bilecik", 11 },
                    { 147, "Bozüyük", 11 },
                    { 148, "Gölpazarı", 11 },
                    { 149, "İnhisar", 11 },
                    { 150, "Osmaneli", 11 },
                    { 151, "Pazaryeri", 11 },
                    { 152, "Söğüt", 11 },
                    { 153, "Yenipazar", 11 },
                    { 154, "Bingöl", 12 },
                    { 155, "Adaklı", 12 },
                    { 156, "Genç", 12 },
                    { 157, "Karlıova", 12 },
                    { 158, "Kığı", 12 },
                    { 159, "Solhan", 12 },
                    { 160, "Yayladere", 12 },
                    { 161, "Yedisu", 12 },
                    { 162, "Bitlis", 13 },
                    { 163, "Adilcevaz", 13 },
                    { 164, "Ahlat", 13 },
                    { 165, "Güroymak", 13 },
                    { 166, "Hizan", 13 },
                    { 167, "Mutki", 13 },
                    { 168, "Tatvan", 13 },
                    { 169, "Bolu", 14 },
                    { 170, "Dörtdivan", 14 },
                    { 171, "Gerede", 14 },
                    { 172, "Göynük", 14 },
                    { 173, "Kıbrıscık", 14 },
                    { 174, "Mengen", 14 },
                    { 175, "Mudurnu", 14 },
                    { 176, "Seben", 14 },
                    { 177, "Yeniçağa", 14 },
                    { 178, "Burdur", 15 },
                    { 179, "Ağlasun", 15 },
                    { 180, "Altınyayla(Dirmil)", 15 },
                    { 181, "Bucak", 15 },
                    { 182, "Çavdır", 15 },
                    { 183, "Çeltikçi", 15 },
                    { 184, "Gölhisar", 15 },
                    { 185, "Karamanlı", 15 },
                    { 186, "Kemer", 15 },
                    { 187, "Tefenni", 15 },
                    { 188, "Yeşilova", 15 },
                    { 189, "Nilüfer", 16 },
                    { 190, "Osmangazi", 16 },
                    { 191, "Yıldırım", 16 },
                    { 192, "Büyükorhan", 16 },
                    { 193, "Gemlik", 16 },
                    { 194, "Gürsu", 16 },
                    { 195, "Harmancık", 16 },
                    { 196, "İnegöl", 16 },
                    { 197, "İznik", 16 },
                    { 198, "Karacabey", 16 },
                    { 199, "Keles", 16 },
                    { 200, "Kestel", 16 },
                    { 201, "Mudanya", 16 },
                    { 202, "Mustafakemalpaşa", 16 },
                    { 203, "Orhaneli", 16 },
                    { 204, "Orhangazi", 16 },
                    { 205, "Yenişehir", 16 },
                    { 206, "Çanakkale", 17 },
                    { 207, "Ayvacık", 17 },
                    { 208, "Bayramiç", 17 },
                    { 209, "Biga", 17 },
                    { 210, "Bozcaada", 17 },
                    { 211, "Çan", 17 },
                    { 212, "Eceabat", 17 },
                    { 213, "Ezine", 17 },
                    { 214, "Gelibolu", 17 },
                    { 215, "Gökçeada(İmroz)", 17 },
                    { 216, "Lapseki", 17 },
                    { 217, "Yenice", 17 },
                    { 218, "Çankırı", 18 },
                    { 219, "Atkaracalar", 18 },
                    { 220, "Bayramören", 18 },
                    { 221, "Çerkeş", 18 },
                    { 222, "Eldivan", 18 },
                    { 223, "Ilgaz", 18 },
                    { 224, "Kızılırmak", 18 },
                    { 225, "Korgun", 18 },
                    { 226, "Kurşunlu", 18 },
                    { 227, "Orta", 18 },
                    { 228, "Şabanözü", 18 },
                    { 229, "Yapraklı", 18 },
                    { 230, "Çorum", 19 },
                    { 231, "Alaca", 19 },
                    { 232, "Bayat", 19 },
                    { 233, "Boğazkale", 19 },
                    { 234, "Dodurga", 19 },
                    { 235, "İskilip", 19 },
                    { 236, "Kargı", 19 },
                    { 237, "Laçin", 19 },
                    { 238, "Mecitözü", 19 },
                    { 239, "Oğuzlar(Karaören)", 19 },
                    { 240, "Ortaköy", 19 },
                    { 241, "Osmancık", 19 },
                    { 242, "Sungurlu", 19 },
                    { 243, "Uğurludağ", 19 },
                    { 244, "Denizli", 20 },
                    { 245, "Acıpayam", 20 },
                    { 246, "Akköy", 20 },
                    { 247, "Babadağ", 20 },
                    { 248, "Baklan", 20 },
                    { 249, "Bekilli", 20 },
                    { 250, "Beyağaç", 20 },
                    { 251, "Bozkurt", 20 },
                    { 252, "Buldan", 20 },
                    { 253, "Çal", 20 },
                    { 254, "Çameli", 20 },
                    { 255, "Çardak", 20 },
                    { 256, "Çivril", 20 },
                    { 257, "Güney", 20 },
                    { 258, "Honaz", 20 },
                    { 259, "Kale", 20 },
                    { 260, "Sarayköy", 20 },
                    { 261, "Serinhisar", 20 },
                    { 262, "Tavas", 20 },
                    { 263, "Sur", 21 },
                    { 264, "Bağlar", 21 },
                    { 265, "Yenişehir", 21 },
                    { 266, "Kayapınar", 21 },
                    { 267, "Bismil", 21 },
                    { 268, "Çermik", 21 },
                    { 269, "Çınar", 21 },
                    { 270, "Çüngüş", 21 },
                    { 271, "Dicle", 21 },
                    { 272, "Eğil", 21 },
                    { 273, "Ergani", 21 },
                    { 274, "Hani", 21 },
                    { 275, "Hazro", 21 },
                    { 276, "Kocaköy", 21 },
                    { 277, "Kulp", 21 },
                    { 278, "Lice", 21 },
                    { 279, "Silvan", 21 },
                    { 280, "Edirne", 22 },
                    { 281, "Enez", 22 },
                    { 282, "Havsa", 22 },
                    { 283, "İpsala", 22 },
                    { 284, "Keşan", 22 },
                    { 285, "Lalapaşa", 22 },
                    { 286, "Meriç", 22 },
                    { 287, "Süleoğlu(Süloğlu)", 22 },
                    { 288, "Uzunköprü", 22 },
                    { 289, "Elazığ", 23 },
                    { 290, "Ağın", 23 },
                    { 291, "Alacakaya", 23 },
                    { 292, "Arıcak", 23 },
                    { 293, "Baskil", 23 },
                    { 294, "Karakoçan", 23 },
                    { 295, "Keban", 23 },
                    { 296, "Kovancılar", 23 },
                    { 297, "Maden", 23 },
                    { 298, "Palu", 23 },
                    { 299, "Sivrice", 23 },
                    { 300, "Erzincan", 24 },
                    { 301, "Çayırlı", 24 },
                    { 302, "İliç(Ilıç)", 24 },
                    { 303, "Kemah", 24 },
                    { 304, "Kemaliye", 24 },
                    { 305, "Otlukbeli", 24 },
                    { 306, "Refahiye", 24 },
                    { 307, "Tercan", 24 },
                    { 308, "Üzümlü", 24 },
                    { 309, "Palandöken", 25 },
                    { 310, "Yakutiye", 25 },
                    { 311, "Aziziye(Ilıca)", 25 },
                    { 312, "Aşkale", 25 },
                    { 313, "Çat", 25 },
                    { 314, "Hınıs", 25 },
                    { 315, "Horasan", 25 },
                    { 316, "İspir", 25 },
                    { 317, "Karaçoban", 25 },
                    { 318, "Karayazı", 25 },
                    { 319, "Köprüköy", 25 },
                    { 320, "Narman", 25 },
                    { 321, "Oltu", 25 },
                    { 322, "Olur", 25 },
                    { 323, "Pasinler", 25 },
                    { 324, "Pazaryolu", 25 },
                    { 325, "Şenkaya", 25 },
                    { 326, "Tekman", 25 },
                    { 327, "Tortum", 25 },
                    { 328, "Uzundere", 25 },
                    { 329, "Odunpazarı", 26 },
                    { 330, "Tepebaşı", 26 },
                    { 331, "Alpu", 26 },
                    { 332, "Beylikova", 26 },
                    { 333, "Çifteler", 26 },
                    { 334, "Günyüzü", 26 },
                    { 335, "Han", 26 },
                    { 336, "İnönü", 26 },
                    { 337, "Mahmudiye", 26 },
                    { 338, "Mihalgazi", 26 },
                    { 339, "Mihalıçcık", 26 },
                    { 340, "Sarıcakaya", 26 },
                    { 341, "Seyitgazi", 26 },
                    { 342, "Sivrihisar", 26 },
                    { 343, "Şahinbey", 27 },
                    { 344, "Şehitkamil", 27 },
                    { 345, "Oğuzeli", 27 },
                    { 346, "Araban", 27 },
                    { 347, "İslahiye", 27 },
                    { 348, "Karkamış", 27 },
                    { 349, "Nizip", 27 },
                    { 350, "Nurdağı", 27 },
                    { 351, "Yavuzeli", 27 },
                    { 352, "Giresun", 28 },
                    { 353, "Alucra", 28 },
                    { 354, "Bulancak", 28 },
                    { 355, "Çamoluk", 28 },
                    { 356, "Çanakçı", 28 },
                    { 357, "Dereli", 28 },
                    { 358, "Doğankent", 28 },
                    { 359, "Espiye", 28 },
                    { 360, "Eynesil", 28 },
                    { 361, "Görele", 28 },
                    { 362, "Güce", 28 },
                    { 363, "Keşap", 28 },
                    { 364, "Piraziz", 28 },
                    { 365, "Şebinkarahisar", 28 },
                    { 366, "Tirebolu", 28 },
                    { 367, "Yağlıdere", 28 },
                    { 368, "Gümüşhane", 29 },
                    { 369, "Kelkit", 29 },
                    { 370, "Köse", 29 },
                    { 371, "Kürtün", 29 },
                    { 372, "Şiran", 29 },
                    { 373, "Torul", 29 },
                    { 374, "Hakkari", 30 },
                    { 375, "Çukurca", 30 },
                    { 376, "Şemdinli", 30 },
                    { 377, "Yüksekova", 30 },
                    { 378, "Antakya", 31 },
                    { 379, "Altınözü", 31 },
                    { 380, "Belen", 31 },
                    { 381, "Dörtyol", 31 },
                    { 382, "Erzin", 31 },
                    { 383, "Hassa", 31 },
                    { 384, "İskenderun", 31 },
                    { 385, "Kırıkhan", 31 },
                    { 386, "Kumlu", 31 },
                    { 387, "Reyhanlı", 31 },
                    { 388, "Samandağ", 31 },
                    { 389, "Yayladağı", 31 },
                    { 390, "Isparta", 32 },
                    { 391, "Aksu", 32 },
                    { 392, "Atabey", 32 },
                    { 393, "Eğridir(Eğirdir)", 32 },
                    { 394, "Gelendost", 32 },
                    { 395, "Gönen", 32 },
                    { 396, "Keçiborlu", 32 },
                    { 397, "Senirkent", 32 },
                    { 398, "Sütçüler", 32 },
                    { 399, "Şarkikaraağaç", 32 },
                    { 400, "Uluborlu", 32 },
                    { 401, "Yalvaç", 32 },
                    { 402, "Yenişarbademli", 32 },
                    { 403, "Akdeniz", 33 },
                    { 404, "Yenişehir", 33 },
                    { 405, "Toroslar", 33 },
                    { 406, "Mezitli", 33 },
                    { 407, "Anamur", 33 },
                    { 408, "Aydıncık", 33 },
                    { 409, "Bozyazı", 33 },
                    { 410, "Çamlıyayla", 33 },
                    { 411, "Erdemli", 33 },
                    { 412, "Gülnar(Gülpınar)", 33 },
                    { 413, "Mut", 33 },
                    { 414, "Silifke", 33 },
                    { 415, "Tarsus", 33 },
                    { 416, "Bakırköy", 34 },
                    { 417, "Bayrampaşa", 34 },
                    { 418, "Beşiktaş", 34 },
                    { 419, "Beyoğlu", 34 },
                    { 420, "Arnavutköy", 34 },
                    { 421, "Eyüp", 34 },
                    { 422, "Fatih", 34 },
                    { 423, "Gaziosmanpaşa", 34 },
                    { 424, "Kağıthane", 34 },
                    { 425, "Küçükçekmece", 34 },
                    { 426, "Sarıyer", 34 },
                    { 427, "Şişli", 34 },
                    { 428, "Zeytinburnu", 34 },
                    { 429, "Avcılar", 34 },
                    { 430, "Güngören", 34 },
                    { 431, "Bahçelievler", 34 },
                    { 432, "Bağcılar", 34 },
                    { 433, "Esenler", 34 },
                    { 434, "Başakşehir", 34 },
                    { 435, "Beylikdüzü", 34 },
                    { 436, "Esenyurt", 34 },
                    { 437, "Sultangazi", 34 },
                    { 438, "Adalar", 34 },
                    { 439, "Beykoz", 34 },
                    { 440, "Kadıköy", 34 },
                    { 441, "Kartal", 34 },
                    { 442, "Pendik", 34 },
                    { 443, "Ümraniye", 34 },
                    { 444, "Üsküdar", 34 },
                    { 445, "Tuzla", 34 },
                    { 446, "Maltepe", 34 },
                    { 447, "Ataşehir", 34 },
                    { 448, "Çekmeköy", 34 },
                    { 449, "Sancaktepe", 34 },
                    { 450, "Büyükçekmece", 34 },
                    { 451, "Çatalca", 34 },
                    { 452, "Silivri", 34 },
                    { 453, "Şile", 34 },
                    { 454, "Sultanbeyli", 34 },
                    { 455, "Aliağa", 35 },
                    { 456, "Balçova", 35 },
                    { 457, "Bayındır", 35 },
                    { 458, "Bornova", 35 },
                    { 459, "Buca", 35 },
                    { 460, "Çiğli", 35 },
                    { 461, "Foça", 35 },
                    { 462, "Gaziemir", 35 },
                    { 463, "Güzelbahçe", 35 },
                    { 464, "Karşıyaka", 35 },
                    { 465, "Kemalpaşa", 35 },
                    { 466, "Konak", 35 },
                    { 467, "Cumaovası(Menderes)", 35 },
                    { 468, "Menemen", 35 },
                    { 469, "Narlıdere", 35 },
                    { 470, "Seferihisar", 35 },
                    { 471, "Selçuk", 35 },
                    { 472, "Torbalı", 35 },
                    { 473, "Urla", 35 },
                    { 474, "Bayraklı", 35 },
                    { 475, "Karabağlar", 35 },
                    { 476, "Bergama", 35 },
                    { 477, "Beydağ", 35 },
                    { 478, "Çeşme", 35 },
                    { 479, "Dikili", 35 },
                    { 480, "Karaburun", 35 },
                    { 481, "Kınık", 35 },
                    { 482, "Kiraz", 35 },
                    { 483, "Ödemiş", 35 },
                    { 484, "Tire", 35 },
                    { 485, "Kars", 36 },
                    { 486, "Akyaka", 36 },
                    { 487, "Arpaçay", 36 },
                    { 488, "Digor", 36 },
                    { 489, "Kağızman", 36 },
                    { 490, "Sarıkamış", 36 },
                    { 491, "Selim", 36 },
                    { 492, "Susuz", 36 },
                    { 493, "Kastamonu", 37 },
                    { 494, "Abana", 37 },
                    { 495, "Ağlı", 37 },
                    { 496, "Araç", 37 },
                    { 497, "Azdavay", 37 },
                    { 498, "Bozkurt", 37 },
                    { 499, "Cide", 37 },
                    { 500, "Çatalzeytin", 37 },
                    { 501, "Daday", 37 },
                    { 502, "Devrekani", 37 },
                    { 503, "Doğanyurt", 37 },
                    { 504, "Hanönü(Gökçeağaç)", 37 },
                    { 505, "İhsangazi", 37 },
                    { 506, "İnebolu", 37 },
                    { 507, "Küre", 37 },
                    { 508, "Pınarbaşı", 37 },
                    { 509, "Seydiler", 37 },
                    { 510, "Şenpazar", 37 },
                    { 511, "Taşköprü", 37 },
                    { 512, "Tosya", 37 },
                    { 513, "Kocasinan", 38 },
                    { 514, "Melikgazi", 38 },
                    { 515, "Talas", 38 },
                    { 516, "Akkışla", 38 },
                    { 517, "Bünyan", 38 },
                    { 518, "Develi", 38 },
                    { 519, "Felahiye", 38 },
                    { 520, "Hacılar", 38 },
                    { 521, "İncesu", 38 },
                    { 522, "Özvatan(Çukur)", 38 },
                    { 523, "Pınarbaşı", 38 },
                    { 524, "Sarıoğlan", 38 },
                    { 525, "Sarız", 38 },
                    { 526, "Tomarza", 38 },
                    { 527, "Yahyalı", 38 },
                    { 528, "Yeşilhisar", 38 },
                    { 529, "Kırklareli", 39 },
                    { 530, "Babaeski", 39 },
                    { 531, "Demirköy", 39 },
                    { 532, "Kofçaz", 39 },
                    { 533, "Lüleburgaz", 39 },
                    { 534, "Pehlivanköy", 39 },
                    { 535, "Pınarhisar", 39 },
                    { 536, "Vize", 39 },
                    { 537, "Kırşehir", 40 },
                    { 538, "Akçakent", 40 },
                    { 539, "Akpınar", 40 },
                    { 540, "Boztepe", 40 },
                    { 541, "Çiçekdağı", 40 },
                    { 542, "Kaman", 40 },
                    { 543, "Mucur", 40 },
                    { 544, "İzmit", 41 },
                    { 545, "Başiskele", 41 },
                    { 546, "Çayırova", 41 },
                    { 547, "Darıca", 41 },
                    { 548, "Dilovası", 41 },
                    { 549, "Kartepe", 41 },
                    { 550, "Gebze", 41 },
                    { 551, "Gölcük", 41 },
                    { 552, "Kandıra", 41 },
                    { 553, "Karamürsel", 41 },
                    { 554, "Tütünçiftlik", 41 },
                    { 555, "Derince", 41 },
                    { 556, "Karatay", 42 },
                    { 557, "Meram", 42 },
                    { 558, "Selçuklu", 42 },
                    { 559, "Ahırlı", 42 },
                    { 560, "Akören", 42 },
                    { 561, "Akşehir", 42 },
                    { 562, "Altınekin", 42 },
                    { 563, "Beyşehir", 42 },
                    { 564, "Bozkır", 42 },
                    { 565, "Cihanbeyli", 42 },
                    { 566, "Çeltik", 42 },
                    { 567, "Çumra", 42 },
                    { 568, "Derbent", 42 },
                    { 569, "Derebucak", 42 },
                    { 570, "Doğanhisar", 42 },
                    { 571, "Emirgazi", 42 },
                    { 572, "Ereğli", 42 },
                    { 573, "Güneysınır", 42 },
                    { 574, "Hadim", 42 },
                    { 575, "Halkapınar", 42 },
                    { 576, "Hüyük", 42 },
                    { 577, "Ilgın", 42 },
                    { 578, "Kadınhanı", 42 },
                    { 579, "Karapınar", 42 },
                    { 580, "Kulu", 42 },
                    { 581, "Sarayönü", 42 },
                    { 582, "Seydişehir", 42 },
                    { 583, "Taşkent", 42 },
                    { 584, "Tuzlukçu", 42 },
                    { 585, "Yalıhüyük", 42 },
                    { 586, "Yunak", 42 },
                    { 587, "Kütahya", 43 },
                    { 588, "Altıntaş", 43 },
                    { 589, "Aslanapa", 43 },
                    { 590, "Çavdarhisar", 43 },
                    { 591, "Domaniç", 43 },
                    { 592, "Dumlupınar", 43 },
                    { 593, "Emet", 43 },
                    { 594, "Gediz", 43 },
                    { 595, "Hisarcık", 43 },
                    { 596, "Pazarlar", 43 },
                    { 597, "Simav", 43 },
                    { 598, "Şaphane", 43 },
                    { 599, "Tavşanlı", 43 },
                    { 600, "Tunçbilek", 43 },
                    { 601, "Malatya", 44 },
                    { 602, "Akçadağ", 44 },
                    { 603, "Arapkir", 44 },
                    { 604, "Arguvan", 44 },
                    { 605, "Battalgazi", 44 },
                    { 606, "Darende", 44 },
                    { 607, "Doğanşehir", 44 },
                    { 608, "Doğanyol", 44 },
                    { 609, "Hekimhan", 44 },
                    { 610, "Kale", 44 },
                    { 611, "Kuluncak", 44 },
                    { 612, "Pötürge", 44 },
                    { 613, "Yazıhan", 44 },
                    { 614, "Yeşilyurt", 44 },
                    { 615, "Manisa", 45 },
                    { 616, "Ahmetli", 45 },
                    { 617, "Akhisar", 45 },
                    { 618, "Alaşehir", 45 },
                    { 619, "Demirci", 45 },
                    { 620, "Gölmarmara", 45 },
                    { 621, "Gördes", 45 },
                    { 622, "Kırkağaç", 45 },
                    { 623, "Köprübaşı", 45 },
                    { 624, "Kula", 45 },
                    { 625, "Salihli", 45 },
                    { 626, "Sarıgöl", 45 },
                    { 627, "Saruhanlı", 45 },
                    { 628, "Selendi", 45 },
                    { 629, "Soma", 45 },
                    { 630, "Turgutlu", 45 },
                    { 631, "Kahramanmaraş", 46 },
                    { 632, "Afşin", 46 },
                    { 633, "Andırın", 46 },
                    { 634, "Çağlayancerit", 46 },
                    { 635, "Ekinözü", 46 },
                    { 636, "Elbistan", 46 },
                    { 637, "Göksun", 46 },
                    { 638, "Nurhak", 46 },
                    { 639, "Pazarcık", 46 },
                    { 640, "Türkoğlu", 46 },
                    { 641, "Mardin", 47 },
                    { 642, "Dargeçit", 47 },
                    { 643, "Derik", 47 },
                    { 644, "Kızıltepe", 47 },
                    { 645, "Mazıdağı", 47 },
                    { 646, "Midyat(Estel)", 47 },
                    { 647, "Nusaybin", 47 },
                    { 648, "Ömerli", 47 },
                    { 649, "Savur", 47 },
                    { 650, "Yeşilli", 47 },
                    { 651, "Muğla", 48 },
                    { 652, "Bodrum", 48 },
                    { 653, "Dalaman", 48 },
                    { 654, "Datça", 48 },
                    { 655, "Fethiye", 48 },
                    { 656, "Kavaklıdere", 48 },
                    { 657, "Köyceğiz", 48 },
                    { 658, "Marmaris", 48 },
                    { 659, "Milas", 48 },
                    { 660, "Ortaca", 48 },
                    { 661, "Ula", 48 },
                    { 662, "Yatağan", 48 },
                    { 663, "Muş", 49 },
                    { 664, "Bulanık", 49 },
                    { 665, "Hasköy", 49 },
                    { 666, "Korkut", 49 },
                    { 667, "Malazgirt", 49 },
                    { 668, "Varto", 49 },
                    { 669, "Nevşehir", 50 },
                    { 670, "Acıgöl", 50 },
                    { 671, "Avanos", 50 },
                    { 672, "Derinkuyu", 50 },
                    { 673, "Gülşehir", 50 },
                    { 674, "Hacıbektaş", 50 },
                    { 675, "Kozaklı", 50 },
                    { 676, "Ürgüp", 50 },
                    { 677, "Niğde", 51 },
                    { 678, "Altunhisar", 51 },
                    { 679, "Bor", 51 },
                    { 680, "Çamardı", 51 },
                    { 681, "Çiftlik(Özyurt)", 51 },
                    { 682, "Ulukışla", 51 },
                    { 683, "Ordu", 52 },
                    { 684, "Akkuş", 52 },
                    { 685, "Aybastı", 52 },
                    { 686, "Çamaş", 52 },
                    { 687, "Çatalpınar", 52 },
                    { 688, "Çaybaşı", 52 },
                    { 689, "Fatsa", 52 },
                    { 690, "Gölköy", 52 },
                    { 691, "Gülyalı", 52 },
                    { 692, "Gürgentepe", 52 },
                    { 693, "İkizce", 52 },
                    { 694, "Karadüz(Kabadüz)", 52 },
                    { 695, "Kabataş", 52 },
                    { 696, "Korgan", 52 },
                    { 697, "Kumru", 52 },
                    { 698, "Mesudiye", 52 },
                    { 699, "Perşembe", 52 },
                    { 700, "Ulubey", 52 },
                    { 701, "Ünye", 52 },
                    { 702, "Rize", 53 },
                    { 703, "Ardeşen", 53 },
                    { 704, "Çamlıhemşin", 53 },
                    { 705, "Çayeli", 53 },
                    { 706, "Derepazarı", 53 },
                    { 707, "Fındıklı", 53 },
                    { 708, "Güneysu", 53 },
                    { 709, "Hemşin", 53 },
                    { 710, "İkizdere", 53 },
                    { 711, "İyidere", 53 },
                    { 712, "Kalkandere", 53 },
                    { 713, "Pazar", 53 },
                    { 714, "Adapazarı", 54 },
                    { 715, "Hendek", 54 },
                    { 716, "Arifiye", 54 },
                    { 717, "Erenler", 54 },
                    { 718, "Serdivan", 54 },
                    { 719, "Akyazı", 54 },
                    { 720, "Ferizli", 54 },
                    { 721, "Geyve", 54 },
                    { 722, "Karapürçek", 54 },
                    { 723, "Karasu", 54 },
                    { 724, "Kaynarca", 54 },
                    { 725, "Kocaali", 54 },
                    { 726, "Pamukova", 54 },
                    { 727, "Sapanca", 54 },
                    { 728, "Söğütlü", 54 },
                    { 729, "Taraklı", 54 },
                    { 730, "Atakum", 55 },
                    { 731, "İlkadım", 55 },
                    { 732, "Canik", 55 },
                    { 733, "Tekkeköy", 55 },
                    { 734, "Alaçam", 55 },
                    { 735, "Asarcık", 55 },
                    { 736, "Ayvacık", 55 },
                    { 737, "Bafra", 55 },
                    { 738, "Çarşamba", 55 },
                    { 739, "Havza", 55 },
                    { 740, "Kavak", 55 },
                    { 741, "Ladik", 55 },
                    { 742, "19Mayıs(Ballıca)", 55 },
                    { 743, "Salıpazarı", 55 },
                    { 744, "Terme", 55 },
                    { 745, "Vezirköprü", 55 },
                    { 746, "Yakakent", 55 },
                    { 747, "Siirt", 56 },
                    { 748, "Baykan", 56 },
                    { 749, "Eruh", 56 },
                    { 750, "Kurtalan", 56 },
                    { 751, "Pervari", 56 },
                    { 752, "Aydınlar", 56 },
                    { 753, "Şirvan", 56 },
                    { 754, "Sinop", 57 },
                    { 755, "Ayancık", 57 },
                    { 756, "Boyabat", 57 },
                    { 757, "Dikmen", 57 },
                    { 758, "Durağan", 57 },
                    { 759, "Erfelek", 57 },
                    { 760, "Gerze", 57 },
                    { 761, "Saraydüzü", 57 },
                    { 762, "Türkeli", 57 },
                    { 763, "Sivas", 58 },
                    { 764, "Akıncılar", 58 },
                    { 765, "Altınyayla", 58 },
                    { 766, "Divriği", 58 },
                    { 767, "Doğanşar", 58 },
                    { 768, "Gemerek", 58 },
                    { 769, "Gölova", 58 },
                    { 770, "Gürün", 58 },
                    { 771, "Hafik", 58 },
                    { 772, "İmranlı", 58 },
                    { 773, "Kangal", 58 },
                    { 774, "Koyulhisar", 58 },
                    { 775, "Suşehri", 58 },
                    { 776, "Şarkışla", 58 },
                    { 777, "Ulaş", 58 },
                    { 778, "Yıldızeli", 58 },
                    { 779, "Zara", 58 },
                    { 780, "Tekirdağ", 59 },
                    { 781, "Çerkezköy", 59 },
                    { 782, "Çorlu", 59 },
                    { 783, "Hayrabolu", 59 },
                    { 784, "Malkara", 59 },
                    { 785, "Marmaraereğlisi", 59 },
                    { 786, "Muratlı", 59 },
                    { 787, "Saray", 59 },
                    { 788, "Şarköy", 59 },
                    { 789, "Tokat", 60 },
                    { 790, "Almus", 60 },
                    { 791, "Artova", 60 },
                    { 792, "Başçiftlik", 60 },
                    { 793, "Erbaa", 60 },
                    { 794, "Niksar", 60 },
                    { 795, "Pazar", 60 },
                    { 796, "Reşadiye", 60 },
                    { 797, "Sulusaray", 60 },
                    { 798, "Turhal", 60 },
                    { 799, "Yeşilyurt", 60 },
                    { 800, "Zile", 60 },
                    { 801, "Trabzon", 61 },
                    { 802, "Akçaabat", 61 },
                    { 803, "Araklı", 61 },
                    { 804, "Arsin", 61 },
                    { 805, "Beşikdüzü", 61 },
                    { 806, "Çarşıbaşı", 61 },
                    { 807, "Çaykara", 61 },
                    { 808, "Dernekpazarı", 61 },
                    { 809, "Düzköy", 61 },
                    { 810, "Hayrat", 61 },
                    { 811, "Köprübaşı", 61 },
                    { 812, "Maçka", 61 },
                    { 813, "Of", 61 },
                    { 814, "Sürmene", 61 },
                    { 815, "Şalpazarı", 61 },
                    { 816, "Tonya", 61 },
                    { 817, "Vakfıkebir", 61 },
                    { 818, "Yomra", 61 },
                    { 819, "Tunceli", 62 },
                    { 820, "Çemişgezek", 62 },
                    { 821, "Hozat", 62 },
                    { 822, "Mazgirt", 62 },
                    { 823, "Nazımiye", 62 },
                    { 824, "Ovacık", 62 },
                    { 825, "Pertek", 62 },
                    { 826, "Pülümür", 62 },
                    { 827, "Şanlıurfa", 63 },
                    { 828, "Akçakale", 63 },
                    { 829, "Birecik", 63 },
                    { 830, "Bozova", 63 },
                    { 831, "Ceylanpınar", 63 },
                    { 832, "Halfeti", 63 },
                    { 833, "Harran", 63 },
                    { 834, "Hilvan", 63 },
                    { 835, "Siverek", 63 },
                    { 836, "Suruç", 63 },
                    { 837, "Viranşehir", 63 },
                    { 838, "Uşak", 64 },
                    { 839, "Banaz", 64 },
                    { 840, "Eşme", 64 },
                    { 841, "Karahallı", 64 },
                    { 842, "Sivaslı", 64 },
                    { 843, "Ulubey", 64 },
                    { 844, "Van", 65 },
                    { 845, "Bahçesaray", 65 },
                    { 846, "Başkale", 65 },
                    { 847, "Çaldıran", 65 },
                    { 848, "Çatak", 65 },
                    { 849, "Edremit(Gümüşdere)", 65 },
                    { 850, "Erciş", 65 },
                    { 851, "Gevaş", 65 },
                    { 852, "Gürpınar", 65 },
                    { 853, "Muradiye", 65 },
                    { 854, "Özalp", 65 },
                    { 855, "Saray", 65 },
                    { 856, "Yozgat", 66 },
                    { 857, "Akdağmadeni", 66 },
                    { 858, "Aydıncık", 66 },
                    { 859, "Boğazlıyan", 66 },
                    { 860, "Çandır", 66 },
                    { 861, "Çayıralan", 66 },
                    { 862, "Çekerek", 66 },
                    { 863, "Kadışehri", 66 },
                    { 864, "Saraykent", 66 },
                    { 865, "Sarıkaya", 66 },
                    { 866, "Sorgun", 66 },
                    { 867, "Şefaatli", 66 },
                    { 868, "Yenifakılı", 66 },
                    { 869, "Yerköy", 66 },
                    { 870, "Zonguldak", 67 },
                    { 871, "Alaplı", 67 },
                    { 872, "Çaycuma", 67 },
                    { 873, "Devrek", 67 },
                    { 874, "Karadenizereğli", 67 },
                    { 875, "Gökçebey", 67 },
                    { 876, "Aksaray", 68 },
                    { 877, "Ağaçören", 68 },
                    { 878, "Eskil", 68 },
                    { 879, "Gülağaç(Ağaçlı)", 68 },
                    { 880, "Güzelyurt", 68 },
                    { 881, "Ortaköy", 68 },
                    { 882, "Sarıyahşi", 68 },
                    { 883, "Bayburt", 69 },
                    { 884, "Aydıntepe", 69 },
                    { 885, "Demirözü", 69 },
                    { 886, "Karaman", 70 },
                    { 887, "Ayrancı", 70 },
                    { 888, "Başyayla", 70 },
                    { 889, "Ermenek", 70 },
                    { 890, "Kazımkarabekir", 70 },
                    { 891, "Sarıveliler", 70 },
                    { 892, "Kırıkkale", 71 },
                    { 893, "Bahşili", 71 },
                    { 894, "Balışeyh", 71 },
                    { 895, "Çelebi", 71 },
                    { 896, "Delice", 71 },
                    { 897, "Karakeçili", 71 },
                    { 898, "Keskin", 71 },
                    { 899, "Sulakyurt", 71 },
                    { 900, "Yahşihan", 71 },
                    { 901, "Batman", 72 },
                    { 902, "Beşiri", 72 },
                    { 903, "Gercüş", 72 },
                    { 904, "Hasankeyf", 72 },
                    { 905, "Kozluk", 72 },
                    { 906, "Sason", 72 },
                    { 907, "Şırnak", 73 },
                    { 908, "Beytüşşebap", 73 },
                    { 909, "Cizre", 73 },
                    { 910, "Güçlükonak", 73 },
                    { 911, "İdil", 73 },
                    { 912, "Silopi", 73 },
                    { 913, "Uludere", 73 },
                    { 914, "Bartın", 74 },
                    { 915, "Amasra", 74 },
                    { 916, "Kurucaşile", 74 },
                    { 917, "Ulus", 74 },
                    { 918, "Ardahan", 75 },
                    { 919, "Çıldır", 75 },
                    { 920, "Damal", 75 },
                    { 921, "Göle", 75 },
                    { 922, "Hanak", 75 },
                    { 923, "Posof", 75 },
                    { 924, "Iğdır", 76 },
                    { 925, "Aralık", 76 },
                    { 926, "Karakoyunlu", 76 },
                    { 927, "Tuzluca", 76 },
                    { 928, "Yalova", 77 },
                    { 929, "Altınova", 77 },
                    { 930, "Armutlu", 77 },
                    { 931, "Çiftlikköy", 77 },
                    { 932, "Çınarcık", 77 },
                    { 933, "Termal", 77 },
                    { 934, "Karabük", 78 },
                    { 935, "Eflani", 78 },
                    { 936, "Eskipazar", 78 },
                    { 937, "Ovacık", 78 },
                    { 938, "Safranbolu", 78 },
                    { 939, "Yenice", 78 },
                    { 940, "Kilis", 79 },
                    { 941, "Elbeyli", 79 },
                    { 942, "Musabeyli", 79 },
                    { 943, "Polateli", 79 },
                    { 944, "Osmaniye", 80 },
                    { 945, "Bahçe", 80 },
                    { 946, "Düziçi", 80 },
                    { 947, "Hasanbeyli", 80 },
                    { 948, "Kadirli", 80 },
                    { 949, "Sumbas", 80 },
                    { 950, "Toprakkale", 80 },
                    { 951, "Düzce", 81 },
                    { 952, "Akçakoca", 81 },
                    { 953, "Cumayeri", 81 },
                    { 954, "Çilimli", 81 },
                    { 955, "Gölyaka", 81 },
                    { 956, "Gümüşova", 81 },
                    { 957, "Kaynaşlı", 81 },
                    { 958, "Yığılca", 81 }
                });

            migrationBuilder.CreateIndex(
                name: "IX_AspNetRoleClaims_RoleId",
                table: "AspNetRoleClaims",
                column: "RoleId");

            migrationBuilder.CreateIndex(
                name: "RoleNameIndex",
                table: "AspNetRoles",
                column: "NormalizedName",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_AspNetUserClaims_UserId",
                table: "AspNetUserClaims",
                column: "UserId");

            migrationBuilder.CreateIndex(
                name: "IX_AspNetUserLogins_UserId",
                table: "AspNetUserLogins",
                column: "UserId");

            migrationBuilder.CreateIndex(
                name: "IX_AspNetUserRoles_RoleId",
                table: "AspNetUserRoles",
                column: "RoleId");

            migrationBuilder.CreateIndex(
                name: "EmailIndex",
                table: "AspNetUsers",
                column: "NormalizedEmail");

            migrationBuilder.CreateIndex(
                name: "UserNameIndex",
                table: "AspNetUsers",
                column: "NormalizedUserName",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_Cities_Name_ProvinceId",
                table: "Cities",
                columns: new[] { "Name", "ProvinceId" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_Cities_ProvinceId",
                table: "Cities",
                column: "ProvinceId");

            migrationBuilder.CreateIndex(
                name: "IX_Organizations_Name",
                table: "Organizations",
                column: "Name");

            migrationBuilder.CreateIndex(
                name: "IX_Provinces_Name",
                table: "Provinces",
                column: "Name",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_Services_CityId",
                table: "Services",
                column: "CityId");

            migrationBuilder.CreateIndex(
                name: "IX_Services_Name",
                table: "Services",
                column: "Name");

            migrationBuilder.CreateIndex(
                name: "IX_Services_OrganizationId",
                table: "Services",
                column: "OrganizationId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "AspNetRoleClaims");

            migrationBuilder.DropTable(
                name: "AspNetUserClaims");

            migrationBuilder.DropTable(
                name: "AspNetUserLogins");

            migrationBuilder.DropTable(
                name: "AspNetUserRoles");

            migrationBuilder.DropTable(
                name: "AspNetUserTokens");

            migrationBuilder.DropTable(
                name: "Services");

            migrationBuilder.DropTable(
                name: "AspNetRoles");

            migrationBuilder.DropTable(
                name: "AspNetUsers");

            migrationBuilder.DropTable(
                name: "Cities");

            migrationBuilder.DropTable(
                name: "Organizations");

            migrationBuilder.DropTable(
                name: "Provinces");
        }
    }
}
